blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://docs.junimoserver.com
    about: Check the documentation
  - name: 💬 Discord
    url: https://discord.gg/w23GVXdSF7
    about: Join us on Discord
