blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/stardew-valley-dedicated-server/server/tree/master/docs
    about: Check the documentation
  - name: 💬 Discord
    url: https://discord.gg/w23GVXdSF7
    about: Join us on Discord
