name: "🚀 Feature request"
description: "Suggest a feature that will improve the project"
labels: ["enhancement", "needs-verification"]
body:
- type: textarea
  id: feature-problem
  attributes:
    label: Is your feature request related to a problem?
    description: Add a clear and concise description of the problem, include possible use cases and alternative solutions you have considered.
  validations:
    required: true
- type: textarea
  id: feature-description
  attributes:
    label: Describe the feature
    description: Add a clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: feature-additional
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request.
  validations:
    required: false
- type: checkboxes
  id: feature-required-info
  attributes:
    label: Final checks
    description: "Before submitting, please make sure you do the following:"
    options:
      - label: Read the [contribution guide](https://github.com/stardew-valley-dedicated-server/server/blob/master/docs/contributing.md).
        required: true
      - label: Check existing [issues](https://github.com/stardew-valley-dedicated-server/server/issues).
        required: true
