name: ci

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - master
      - "!v[0-9]*"

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

# Ensure it only runs one instance for the given PR/commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Cache artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          retention-days: 3
          name: dist
          path: .output/mods/JunimoServer/

  # release-nightly:
  #   if: |
  #     github.repository_owner == 'stardew-valley-dedicated-server' &&
  #     github.event_name == 'push' &&
  #     !contains(github.event.head_commit.message, '[skip-release]') &&
  #     !startsWith(github.event.head_commit.message, 'docs')
  #   concurrency:
  #     group: release
  #   permissions:
  #     id-token: write
  #   needs:
  #     - build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 20

  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  #       with:
  #         fetch-depth: 0

  #     - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0

  #     - name: Install dependencies
  #       run: pnpm install

  #     - name: Restore artifacts
  #       uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
  #       with:
  #         name: dist
  #         path: .output/mods/JunimoServer/

  #     - name: Release Edge
  #       run: ./scripts/release-edge.sh ${{ github.ref == 'refs/heads/main' && 'latest' || '3x' }}
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  #         NPM_CONFIG_PROVENANCE: true

  release-pr:
    if: |
        github.repository_owner == 'stardew-valley-dedicated-server' &&
        github.event_name != 'push'
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0

      - name: Install dependencies
        run: pnpm install

      - name: Restore artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: dist
          path: .output/mods/JunimoServer/

      # TODO: Prepare and create release PR
      - run: make release pr
