name: release

on:
  push:
    tags:
      - "v*"

# Clear default permissions of GITHUB_TOKEN and set them per job, for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  release:
    if: |
      github.repository == 'nuxt/nuxt' &&
      (startsWith(github.event.head_commit.message, 'v3.') || startsWith(github.event.head_commit.message, 'v4.'))
    concurrency:
      group: release
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0

      - name: Install dependencies
        run: pnpm install

      - name: Release
        run: ./scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.RELEASE_NODE_AUTH_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
