context.properties = {
    support.dbus = false
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}

context.modules = [
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-adapter }
]

context.objects = [
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "null-sink"
            media.class      = "Audio/Sink"
            audio.position   = [ FL FR ]
        }
    }
]
