#!/bin/sh

# Disable composition manager as it might cause lag and tearing in the game, see:
# https://wiki.archlinux.org/title/Steam/Troubleshooting#Killing_standalone_compositors_when_launching_games

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "true"